### ISSUE TITLE
Trace the eventdispatcher teardown steps

### ISSUE THREAD

**Issue by adorokhine** [google/mobly#33]
The event dispatcher teardown has some issues:

            if event_name == "EventDispatcherShutdown":
                self._sl4a.closeSl4aSession()

This throws an error, but the error is squashed because it's done inside a Future whose result is never checked.

    self.poller.set_result("Done")

This is a private API for Executor implementations and should not be called externally.

     # The polling thread is guaranteed to finish after a max of 60 seconds,
     # so we don't wait here.
     self.executor.shutdown(wait=False)

Don't quite understand the comment here. Doesn't this mean the polling loop might still try to handle events after the server is torn down? And, couldn't this keep the python interpreter open for up to 60 seconds after the test ends?

        if self.sl4a:
            self.sl4a.closeSl4aSession()
            self.sl4a.close()
            self.sl4a = None
        if self.ed:
            self.ed.clean_up()
            self.ed = None

It's awkward and surprising that ed is torn down after its host sl4a session. Actually I'm surprised this works. Won't any sl4a commands clean_up tries to issue fail?

**Comment by xpconanfan** [comment]
To clarify the teardown mechanism:

Current structure:
There are two connections (droid and ed._sl4a) to the device-side session, each connection holds its own reader/writer instances, but both connections share the same sets of facade objects because they share the same RpcReceiverManager instances.

Two loops (while True) need to be broken out of: the RPC server loop on the device side, and the event polling loop in 'ed' on the Python side.

During teardown, the workflow is:
1. droid.closeSl4aSession, 'droid' sends shutdown signal to its connection instance on device side.
2. 'droid's connection instance gets the signal, sends 'EventDispatcherShutdown' event to 'ed', shuts down its own reader/writer.
3. 'ed' gets the shutdown signal, sends close signal to its own connection instance on device side, breaks out of the polling loop.
4. 'ed''s connection instance on the device side executes the shutdown signal, sends an extra 'EventDispatcherShutdown' event, closes its own reader/writer.
5. The extra 'EventDispatcherShutdown' event is never polled.

Note that ed.clean_up does not actually send anything to the device side.

The goal is to safely exist both loops, one on the device side, one on the host side.

Given the context, how would you like to improve the mechanism?

**Comment by xpconanfan** [comment]
Assigning to Alex for suggestions.

**Comment by xpconanfan** [comment]
Do we still want this?

**Comment by adorokhine** [comment]
If we're deprioritizing sl4a and pushing people to mbs I'm ok with leaving the event dispatcher alone.

**Comment by xpconanfan** [comment]
Ok, let's close this.
I'd rather spend time writing a system priv snippet implementation than figuring this out...
