### ISSUE TITLE
Mobly and ACTS

### ISSUE THREAD

**Issue by gebotecu** [google/mobly#666]
Dear 

1. I have a question about Mobly and ACTS. I learn Mobly and ACTS, I noticed that the structure of the of them is very similar. And ATCS install require Mobly. Would you like to  help explain the relationship and scenarios for test?

2. Mobly can use sl4a and Mobly Snippet  to controller Android device. What scenarios are the two approaches applied to respectively?

**Comment by xpconanfan** [comment]
1. We are converging the frameworks of ACTS and Mobly to reduce duplication :)
Going forward:
* The name "ACTS" will refer to the collection of *test cases*
* These test cases will use Mobly's runner.

2. Mobly provides a generic RPC library [MSL](https://github.com/google/mobly-snippet-lib) so a user can create and own their own device-side APKs to be triggered by host-side Mobly test via the RPC clients.

In the context of AOSP code base (not the github sl4a), SL4A is like a special snippet APK that lives inside of AOSP and has privileged access to not just system APIs but also hidden APIs.

If you are creating a regular test, you likely do not need SL4A's power.
You only need SL4A if you are an Android device OEM trying to test very deep into the stack, which requires special access to platform APIs that are not exposed.

Also SL4A has a lot of logic in it. It's probably cleaner and more maintainable to create your own snippet instead of dumping more into SL4A.

**Comment by gebotecu** [comment]
Dear 

Thank you for your reply. I have antoher 2 questions:
1)ACTS was designed for comms testing at the beginning, but its architecture is not only suitable for comms testing, but also for APP testing , etc. Is there any plan extension in the future?

2) Android Bootcamp 2020 Engineering Productivity Talk 'Comms Testing'

Consolidated with Mobly in early Q2 -
https://github.com/google/mobly. Tests will be fully compatible.
■ Enables additional testing libraries including app-level tests and
non user-debug level testing

Does this mean that you will converge the frameworks of ACTS and Mobly in early Q2?
And what does  'Enables additional testing libraries including app-level tests and
non user-debug level testing' mean? What is app-level tests and non user-debug level testing. Would you like give me an example to help me understand this.

Thank you.

**Comment by gebotecu** [comment]
Dear

Thank you for your reply. I have antoher 2 questions:
1. ACTS was designed for comms testing at the beginning, but its architecture is not only suitable   for comms testing, but also for APP testing , etc. Is there any plan extension in the future?

2.Android Bootcamp 2020 Engineering Productivity Talk 'Comms Testing'
   Consolidated with Mobly in early Q2 -
   https://github.com/google/mobly. Tests will be fully compatible.
   ■ Enables additional testing libraries including app-level tests and
   non user-debug level testing

  1) Does this mean that you will converge the frameworks of ACTS and Mobly in early Q2?
  And what does 'Enables additional testing libraries including app-level tests and
  non user-debug level testing' mean? 
  2) What is app-level tests and non user-debug level testing. Would you like give me an example 
  to  help me understand this.
Look forward to your reply。Thank you.

**Comment by xpconanfan** [comment]
1. Use Mobly for your tests if you are not adding/modifying ACTS tests. As ACTS will become a set of test cases, not a framework.
2.1 ACTS tests already run on Mobly today.
2.2 ACTS tests heavily rely on system privilege, and lack coverage for public APIs, which means all tests can pass yet apps fail when trying to use the public APIs. So I guess that means they might add more coverage exercising Android's public APIs as a regular app would, without system privilege.

Also, this is not customer service for ACTS.
Please direct ACTS related questions to the ACTS site.
